#!/bin/bash
verde='\033[32m'
blanco='\033[37m'
rojo='\033[31m'
echo -e "${verde}
┌══════════════════════════┐
█ ${blanco}OBTENIENDO IP DEL ISP... ${verde}█
└══════════════════════════┘"${blanco}
ShowIP=$(w3m -dump https://ipapi.co/ip)
echo -e "${verde}
┌═════════════════════┐
█ ${blanco}IP DEL ISP OBTENIDA ${verde}█
└═════════════════════┘
┃
└═>>>${blanco} ${ShowIP}
"
